name: MiscCmds
version: 1.1
author: AvhiDh
main: com.github.AvhiDh.MiscCmds
api-version: '1.19'
commands:
  freeze:
    description: Freeze player from moving
    usage: /freeze <player>
    permission: MiscCmds.Freeze
  deathspot:
    description: Get Player's DeathSpot
    usage: /deathspot, /ds
    aliases: ds
    permission: deathspot.use
  h:
    description: Shortcut for /helpop
    usage: /hp <message>
    permission: essentials.helpop
  staffchat:
    description: Staff Chat
    usage: /sc <message>
    aliases: sc
    permission: spartan.staff_chat